name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: select terraform action
        options:
        - apply
        - destroy
        required: true
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    env:
      # AWS secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.peteraccesskey }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.petersecret }}
    defaults:
      run:
        working-directory: ./src 
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2  

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      #uses: hashicorp/setup-terraform@v1
      #id: init
      run: terraform init
      working-directory: ./src 
      
    - name: Terraform validate
      id: validate
      run: terraform validate
      working-directory: ./src 
    - name: Terraform plan
      #uses: hashicorp/setup-terraform@v1
      id: plan
      run: terraform plan
      working-directory: ./src 
    - name: Terraform apply
      id: apply
      if: ${{ github.event.inputs.terraform_action == 'apply' }}
      #uses: hashicorp/setup-terraform@v1
      run: terraform apply -auto-approve
      working-directory: ./src  
    - name: Terraform destroy
      id: destroy 
      if: ${{ github.event.inputs.terraform_action == 'destroy' }}
      run: terraform destroy -auto-approve 
      working-directory: ./src 